name: test and audi workflow
on:
  push:
    branches:
      - develop
      - master
      - main
  pull_request:
    branches:
      - develop
      - mater
      - main

jobs: 
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i 
      - run: npm audit --production --level-critical
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm run test:ci